<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Mds-MacBook-Pro.home" name="testUnit.LogInTest" tests="9" failures="0" timestamp="25 Jun 2020 05:12:19 GMT" time="37.395" errors="1">
  <testcase name="logIntest_In_toKohls" time="2.368" classname="testUnit.LogInTest">
    <skipped/>
  </testcase> <!-- logIntest_In_toKohls -->
  <testcase name="logIntest_In_toKohls" time="4.597" classname="testUnit.LogInTest"/>
  <testcase name="logIntest_In_toKohls" time="2.905" classname="testUnit.LogInTest">
    <skipped/>
  </testcase> <!-- logIntest_In_toKohls -->
  <testcase name="logIntest_In_toKohls" time="3.231" classname="testUnit.LogInTest"/>
  <testcase name="logIntest_In_toKohls" time="13.025" classname="testUnit.LogInTest"/>
  <testcase name="logIntest_In_toKohls" time="2.891" classname="testUnit.LogInTest"/>
  <testcase name="logIntest_In_toKohls" time="2.624" classname="testUnit.LogInTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testUnit.LogInTest.logIntest_In_toKohls(LogInTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- logIntest_In_toKohls -->
  <testcase name="logIntest_In_toKohls" time="5.754" classname="testUnit.LogInTest">
    <skipped/>
  </testcase> <!-- logIntest_In_toKohls -->
  <testcase name="logIntest_IntoKohls" classname="testUnit.LogInTest">
    <skipped/>
  </testcase> <!-- logIntest_IntoKohls -->
</testsuite> <!-- testUnit.LogInTest -->
